targets:
  $default:
    builders:
      firestore_converter_generator:
        enabled: true
        generate_for:
          - lib/*.dart
        options:
          ignore_for_file:
            - "type=lint"

builders:
  firestore_converter_generator:
    import: "package:firestore_converter_generator/firestore_converter_generator.dart"
    builder_factories: ["firestoreConverterGeneratorFactory"]
    build_extensions:
      .dart: [.firestore_converter.dart]
    auto_apply: dependents
    build_to: source
