name: firestore_converter
description: >
  Annotation @FirestoreConverter({String? defaultPath}) for automatic Firestore .withConverter code generation.
version: 1.0.9
repository: https://github.com/Aurangseb/firestore_converter
issue_tracker: https://github.com/Aurangseb/firestore_converter/issues

# This package supports all platforms that the package cloud_firestore supports.
# pub.dev does not detect them correctly, therefore they are fixed here manually.
# Right now, only Linux is not supported by cloud_firestore.
platforms:
  android:
  ios:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
#  collection: ^1.15.0
#  json_annotation: ^4.6.0
  meta: ^1.7.0

# dev_dependencies:
#  build_runner: ^2.3.3
#  json_serializable: ^6.3.2
#  test: ^1.21.0
